"""Cloud Realtime subsystem: provider-neutral speech-to-speech foundation."""

from chatwaifu_runtime.realtime.cloud.contracts import (
    AssistantTranscriptEvent,
    CloudRealtimeBackend,
    CloudRealtimeSession,
    InputAudioCommittedEvent,
    OutputAudioEvent,
    ProviderErrorEvent,
    RealtimeCapabilities,
    RealtimeContextComponent,
    RealtimeContextPatch,
    RealtimeInputAudioFrame,
    RealtimeOutputAudioFrame,
    RealtimeProviderError,
    RealtimeProviderEvent,
    RealtimeSessionLineage,
    RealtimeSessionOpenRequest,
    RealtimeTranscriptCandidate,
    RealtimeUsage,
    ResponseCancelledEvent,
    ResponseCompletedEvent,
    ResponseStartedEvent,
    SessionClosedEvent,
    SessionDegradedEvent,
    SessionReadyEvent,
    UsageRecordedEvent,
    UserTranscriptEvent,
)
from chatwaifu_runtime.realtime.cloud.coordinator import (
    CloudRealtimeCoordinator,
    InMemoryDomainSink,
    InMemoryMediaSink,
    RealtimeDomainSink,
    RealtimeMediaSink,
)
from chatwaifu_runtime.realtime.cloud.fake import (
    FakeCloudRealtimeBackend,
    FakeCloudRealtimeSession,
)
from chatwaifu_runtime.realtime.cloud.mirror import (
    GenerationBinding,
    RealtimeSessionMirror,
)

__all__ = [
    "AssistantTranscriptEvent",
    "CloudRealtimeBackend",
    "CloudRealtimeCoordinator",
    "CloudRealtimeSession",
    "FakeCloudRealtimeBackend",
    "FakeCloudRealtimeSession",
    "GenerationBinding",
    "InMemoryDomainSink",
    "InMemoryMediaSink",
    "InputAudioCommittedEvent",
    "OutputAudioEvent",
    "ProviderErrorEvent",
    "RealtimeCapabilities",
    "RealtimeContextComponent",
    "RealtimeContextPatch",
    "RealtimeDomainSink",
    "RealtimeInputAudioFrame",
    "RealtimeMediaSink",
    "RealtimeOutputAudioFrame",
    "RealtimeProviderError",
    "RealtimeProviderEvent",
    "RealtimeSessionLineage",
    "RealtimeSessionMirror",
    "RealtimeSessionOpenRequest",
    "RealtimeTranscriptCandidate",
    "RealtimeUsage",
    "ResponseCancelledEvent",
    "ResponseCompletedEvent",
    "ResponseStartedEvent",
    "SessionClosedEvent",
    "SessionDegradedEvent",
    "SessionReadyEvent",
    "UsageRecordedEvent",
    "UserTranscriptEvent",
]
