"""Durable autonomy policy and counters. Ordinary dialogue remains ephemeral."""

from datetime import datetime
from typing import Protocol
from uuid import UUID

from chatwaifu_protocol.agent import DecisionRecord, GroupAutonomyPolicy


class BehaviorRepository(Protocol):
    async def get(self, route_id: UUID) -> GroupAutonomyPolicy | None: ...
    async def save(self, policy: GroupAutonomyPolicy, expected_revision: int) -> bool: ...
    async def reserve(
        self, policy: GroupAutonomyPolicy, now: datetime, *, speech: bool
    ) -> bool: ...
    async def next_observation(self, policy: GroupAutonomyPolicy, now: datetime) -> datetime: ...
    async def quiet_until(self, route_id: UUID) -> datetime | None: ...
    async def set_quiet(self, route_id: UUID, until: datetime) -> None: ...
    async def mark_turn(self, turn_id: UUID, route_id: UUID, policy_revision: int) -> bool: ...
    async def authorize_turn(self, turn_id: UUID) -> bool: ...
    async def record(
        self, policy: GroupAutonomyPolicy, decision: DecisionRecord, now: datetime
    ) -> None: ...
    async def recent(self, route_id: UUID) -> list[DecisionRecord]: ...
