"""Owner development policy and one-per-day candidate reservation boundary."""

from typing import Protocol
from uuid import UUID

from chatwaifu_protocol.agent import AgentDevelopmentPolicy, CandidateFeature


class DevelopmentRepository(Protocol):
    async def policy(self) -> AgentDevelopmentPolicy: ...
    async def configure(self, policy: AgentDevelopmentPolicy, expected_revision: int) -> bool: ...
    async def reserve(self, candidate: CandidateFeature, day: str) -> bool: ...
    async def get(self, candidate_id: UUID) -> CandidateFeature | None: ...
    async def list(self) -> list[CandidateFeature]: ...
    async def save(self, candidate: CandidateFeature, expected_revision: int) -> bool: ...
