"""Persistence boundary for durable goals and operation journals."""

from typing import Protocol
from uuid import UUID

from chatwaifu_protocol.agent import AgentEvent, AgentTask, AgentTaskPage
from chatwaifu_protocol.base import JsonObject


class AgentTaskRepository(Protocol):
    async def create(self, task: AgentTask) -> None: ...
    async def get(self, task_id: UUID) -> AgentTask | None: ...
    async def save(self, task: AgentTask, expected_revision: int) -> bool: ...
    async def page(self, scope: str | None, cursor: str | None = None) -> AgentTaskPage: ...
    async def begin_step(self, task_id: UUID, key: str, record: JsonObject) -> bool: ...
    async def finish_step(self, task_id: UUID, key: str, record: JsonObject) -> None: ...
    async def steps(self, task_id: UUID) -> list[JsonObject]: ...
    async def enqueue_event(self, event: AgentEvent) -> bool: ...
    async def settle_event(self, event_id: UUID) -> None: ...
    async def pending_events(self) -> list[AgentEvent]: ...
