"""Persistence ports owned by the Runtime Skills domain."""

from __future__ import annotations

from collections.abc import Mapping
from typing import Protocol
from uuid import UUID

from chatwaifu_protocol.errors import StructuredError

type Record = Mapping[str, object]


class SkillRunRepository(Protocol):
    """Run lifecycle and bounded tool-call audit persistence."""

    async def expire_nonterminal_runs(self, error: StructuredError, now: str) -> None: ...
    async def has_active_reference(self, column: str, value: str) -> bool: ...
    async def create_run(self, values: Mapping[str, object]) -> None: ...
    async def run(self, run_id: UUID) -> Record | None: ...
    async def run_for_confirmation(self, request_id: UUID) -> Record | None: ...
    async def runs_for_session(self, session_id: UUID, limit: int) -> list[Record]: ...
    async def mark_run_cancelling(self, run_id: UUID, now: str) -> None: ...
    async def mark_run_running(self, run_id: UUID, now: str) -> None: ...
    async def complete_run(self, run_id: UUID, result_json: str, now: str) -> None: ...
    async def fail_run(self, run_id: UUID, error_json: str, now: str) -> None: ...
    async def cancel_run(self, run_id: UUID, now: str) -> None: ...
    async def start_tool_call(self, values: Mapping[str, object]) -> None: ...
    async def finish_tool_call(self, values: Mapping[str, object]) -> None: ...


class PermissionRepository(Protocol):
    """Permission grants and single-decision confirmation persistence."""

    async def has_permission_grant(
        self,
        *,
        principal: str,
        session_id: UUID,
        skill_id: str,
        capability: str,
        permission: str,
        subject_fingerprint: str,
        now: str,
    ) -> bool: ...
    async def create_permission_request(self, values: Mapping[str, object]) -> None: ...
    async def permission_request(self, request_id: UUID) -> Record | None: ...
    async def decide_permission_request(
        self,
        *,
        request_id: UUID,
        decision: str,
        decided_by: str,
        decided_at: str,
        session_id: UUID,
        grants: list[str],
    ) -> bool: ...
    async def pending_permission_requests(self, session_id: UUID, now: str) -> list[Record]: ...
    async def expire_permission_for_run(self, run_id: UUID, now: str) -> None: ...
    async def expire_pending_permissions(self, now: str) -> list[UUID]: ...


class PluginRepository(Protocol):
    """Installed plugin package registration persistence."""

    async def list_plugin_records(self) -> list[Record]: ...
    async def plugin_record(self, plugin_id: str) -> Record | None: ...
    async def insert_plugin(self, values: Mapping[str, object]) -> None: ...
    async def set_plugin_enabled(self, plugin_id: str, enabled: bool, now: str) -> bool: ...
    async def set_plugin_sandbox_backend(
        self, plugin_id: str, backend: str | None, limits_json: str, now: str
    ) -> bool: ...
    async def delete_plugin(self, plugin_id: str) -> bool: ...


class McpConnectionRepository(Protocol):
    """Persisted MCP Host connection metadata; never bearer-token bytes."""

    async def list_mcp_connection_records(self) -> list[Record]: ...
    async def mcp_connection_record(self, connection_id: UUID) -> Record | None: ...
    async def insert_mcp_connection(self, values: Mapping[str, object]) -> None: ...
    async def update_mcp_connection(self, values: Mapping[str, object]) -> bool: ...
    async def delete_mcp_connection(self, connection_id: UUID) -> bool: ...
    async def mcp_connection_revision(self, connection_id: UUID) -> int | None: ...
    async def reconcile_mcp_secret_flags(self, configured_ids: set[str]) -> None: ...
    async def mark_mcp_test_error(
        self,
        connection_id: UUID,
        message: str,
        sandbox_backend: str | None,
        sandbox_limits_json: str,
        now: str,
    ) -> None: ...
    async def mark_mcp_test_ready(
        self,
        connection_id: UUID,
        capabilities_json: str,
        sandbox_backend: str | None,
        sandbox_limits_json: str,
        now: str,
    ) -> None: ...


class RuntimeSkillRepository(
    SkillRunRepository,
    PermissionRepository,
    PluginRepository,
    McpConnectionRepository,
    Protocol,
):
    """Composition-root convenience port for the complete Runtime Skills domain."""
